name: Wheel Builder
on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  macos:
    runs-on: ${{ matrix.PYTHON.RUNNER }}
    strategy:
      fail-fast: false
      matrix:
        PYTHON:
          - VERSION: '3.8'
            ABI_VERSION: 'cp36'
            ARCH: 'x86_64'
            RUNNER: 'macos-15-intel'
            DOWNLOAD_URL: 'https://www.python.org/ftp/python/3.8.2/python-3.8.2-macosx10.9.pkg'
            BIN_PATH: '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3'
            OPENSSL_ARTIFACT: 'openssl-macos-x86-64'
            CFLAGS_MIN: '-mmacosx-version-min=10.10 -march=core2'
          - VERSION: '3.11'
            ABI_VERSION: 'cp36'
            ARCH: 'arm64'
            RUNNER: 'macos-14'
            DOWNLOAD_URL: 'https://www.python.org/ftp/python/3.11.9/python-3.11.9-macos11.pkg'
            BIN_PATH: '/Library/Frameworks/Python.framework/Versions/3.11/bin/python3'
            OPENSSL_ARTIFACT: 'openssl-macos-arm64'
            CFLAGS_MIN: '-mmacosx-version-min=11.0'
    name: "${{ matrix.PYTHON.VERSION }} ABI ${{ matrix.PYTHON.ABI_VERSION }} macOS ${{ matrix.PYTHON.ARCH }}"
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl "$PYTHON_DOWNLOAD_URL" -o python.pkg
          sudo installer -pkg python.pkg -target /
        env:
          PYTHON_DOWNLOAD_URL: ${{ matrix.PYTHON.DOWNLOAD_URL }}
      - run: ${{ matrix.PYTHON.BIN_PATH }} -m pip install -U virtualenv requests
      - name: Download OpenSSL
        run: ${{ matrix.PYTHON.BIN_PATH }} .github/workflows/download_openssl.py macos ${{ matrix.PYTHON.OPENSSL_ARTIFACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable

      - run: ${{ matrix.PYTHON.BIN_PATH }} -m virtualenv venv
      - run: venv/bin/pip install -U pip wheel cffi six ipaddress setuptools-rust
      - name: Build the wheel
        run: |
          CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS="1" \
              LDFLAGS="${HOME}/${{ matrix.PYTHON.OPENSSL_ARTIFACT }}/lib/libcrypto.a ${HOME}/${{ matrix.PYTHON.OPENSSL_ARTIFACT }}/lib/libssl.a" \
              CFLAGS="-I${HOME}/${{ matrix.PYTHON.OPENSSL_ARTIFACT }}/include ${{ matrix.PYTHON.CFLAGS_MIN }}" \
              venv/bin/python setup.py bdist_wheel --py-limited-api=${{ matrix.PYTHON.ABI_VERSION }}
          mkdir wheelhouse && mv dist/cryptography*.whl wheelhouse
      - run: ls -lA wheelhouse/
      - run: venv/bin/pip install -f wheelhouse --no-index cryptography
      - run: |
          venv/bin/python -c "from cryptography.hazmat.backends.openssl.backend import backend;print('Loaded: ' + backend.openssl_version_text());print('Linked Against: ' + backend._ffi.string(backend._lib.OPENSSL_VERSION_TEXT).decode('ascii'))"

      - run: mkdir cryptography-wheelhouse
      - run: mv wheelhouse/cryptography*.whl cryptography-wheelhouse/
      - uses: actions/upload-artifact@v4
        with:
          name: "cryptography-${{ github.event.inputs.version }}-macOS-${{ matrix.PYTHON.ARCH }}-${{ matrix.PYTHON.ABI_VERSION }}"
          path: cryptography-wheelhouse/

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        WINDOWS:
          - {ARCH: 'x86', WINDOWS: 'win32', RUST_TRIPLE: 'i686-pc-windows-msvc'}
          - {ARCH: 'x64', WINDOWS: 'win64', RUST_TRIPLE: 'x86_64-pc-windows-msvc'}
        PYTHON:
          - {VERSION: "3.8", MSVC_VERSION: "2019", "ABI_VERSION": "cp36"}
    name: "${{ matrix.PYTHON.VERSION }} ${{ matrix.WINDOWS.WINDOWS }} ${{ matrix.PYTHON.ABI_VERSION }}"
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ matrix.PYTHON.VERSION }}
          architecture: ${{ matrix.WINDOWS.ARCH }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.49.0
          override: true
          default: true
          target: ${{ matrix.WINDOWS.RUST_TRIPLE }}

      - run: pip install requests
      - name: Download OpenSSL
        run: |
            python .github/workflows/download_openssl.py windows openssl-windows-${{ matrix.WINDOWS.ARCH }}
            echo "INCLUDE=C:/openssl-windows-${{ matrix.WINDOWS.ARCH }}/include;$INCLUDE" >> $GITHUB_ENV
            echo "LIB=C:/openssl-windows-${{ matrix.WINDOWS.ARCH }}/lib;$LIB" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - run: python -m pip install -U pip wheel cffi six ipaddress setuptools-rust
      - run: python setup.py bdist_wheel --py-limited-api=${{ matrix.PYTHON.ABI_VERSION }} && mkdir wheelhouse && mv dist/cryptography*.whl wheelhouse
      - run: DIR wheelhouse/
      - run: pip install -f wheelhouse --no-index cryptography
      - name: Print the OpenSSL we built and linked against
        run: |
            python -c "from cryptography.hazmat.backends.openssl.backend import backend;print('Loaded: ' + backend.openssl_version_text());print('Linked Against: ' + backend._ffi.string(backend._lib.OPENSSL_VERSION_TEXT).decode('ascii'))"

      - run: mkdir cryptography-wheelhouse
      - run: move wheelhouse\cryptography*.whl cryptography-wheelhouse\
      - uses: actions/upload-artifact@v4
        with:
          name: "cryptography-${{ github.event.inputs.version }}-${{ matrix.WINDOWS.WINDOWS }}-${{ matrix.PYTHON.VERSION }}-${{ matrix.PYTHON.ABI_VERSION}}"
          path: cryptography-wheelhouse\
      # - name: "pytest"
      #   run: |
      #     python -m pip install iso8601 pretend pytz hypothesis pytest cryptography_vectors==3.4
      #     python -m pytest tests -k "not test_vector_version"
